# .shed.yml supporting automatic pushes.
owner: recetox
categories:
  - MS-utils
repositories:
  biotransformer:
    description: "Convertor for different chemical identifiers."
    include:
      - chem_identifier_converterDocker.xml
toolshed:
  - localhost:9009

