# .shed.yml supporting automatic pushes.
owner: recetox
categories:
  - ZZ-test2
repositories:
  chem_identifier_converter:
    description: "Convertor for different chemical identifiers."
    include:
      - chem_identifier_converterDocker.xml
toolshed:
  - localhost:9009

